# Source: minecraft-server/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  labels:
    app.kubernetes.io/name: minecraft-server
spec:
  type: NodePort
  ports:
    - port: 30069
      targetPort: 25565
      nodePort: 30069
      protocol: TCP
      name: game-port
  selector:
    app.kubernetes.io/name: minecraft-server
---
# Source: minecraft-server/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft-server
  labels:
    app.kubernetes.io/name: minecraft-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minecraft-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minecraft-server
    spec:
      containers:
        - name: minecraft-server
          image: mridulganga/minecraft-server
          imagePullPolicy: Always
          env:
            - name: EULA
              value: "TRUE"
            - name: ONLINE_MODE
              value: "FALSE"
            - name: PVP
              value: "FALSE"
            - name: SERVER_NAME
              value: "MG Minecraft Server"
            - name: MODE
              value: creative
            - name: DIFFICULTY 
              value: peaceful
            - name: SPAWN_PROTECTION
              value: "4"
            - name: SEED
              value: "8638613833825887773"
            - name: OPS
              value: "doomoverlord,mgmgmg,mg,blaze"
          ports:
            - name: game-port
              containerPort: 25565
              protocol: TCP