#!/bin/bash

. ${SCRIPTS:-/}start-utils

umask 0002
chmod g+w /data

if [ $(id -u) = 0 ]; then
  runAsUser=minecraft
  runAsGroup=minecraft

  if [[ -v UID ]]; then
    if [[ $UID != 0 ]]; then
      if [[ $UID != $(id -u minecraft) ]]; then
        log "Changing uid of minecraft to $UID"
        usermod -u $UID minecraft
      fi
    else
      runAsUser=root
    fi
  fi

  if [[ -v GID ]]; then
    if [[ $GID != 0 ]]; then
      if [[ $GID != $(id -g minecraft) ]]; then
        log "Changing gid of minecraft to $GID"
        groupmod -o -g $GID minecraft
      fi
    else
      runAsGroup=root
    fi
  fi

  if [ -z "$WORLD_REPO" ]
  then
        echo "\$No World repo provided, will not backup"

  else
        # https://github.com/salty-outlaws/world-zero
        git clone $WORLD_REPO
        mv world-zero /data/world

          sed -i "s/dummy-token/$GITHUB_TOKEN/g" /backup-script.sh
          sed -i "s/dummy-user/$GITHUB_USER/g" /backup-script.sh
          sed -i "s/dummy-email/$GITHUB_EMAIL/g" /backup-script.sh

          /usr/bin/crontab /tmp/crontab.txt
          crond
  fi

  if [ -z "$MODS_SCRIPT" ]
  then
    echo "Not instaling mods"
  else
    log "Installing mods"
    mkdir -p /data/mods
    # https://salty-outlaws.github.io/mc-mods-cdn/install.sh
    curl -s $MODS_SCRIPT | bash
  fi

  log "Changing ownership of /data to $UID ..."
  chown -R ${runAsUser}:${runAsGroup} /data

  if [[ ${SKIP_NSSWITCH_CONF^^} != TRUE ]]; then
    echo 'hosts: files dns' > /etc/nsswitch.conf
  fi

  exec su-exec ${runAsUser}:${runAsGroup} ${SCRIPTS:-/}start-configuration $@
else
  exec ${SCRIPTS:-/}start-configuration $@
fi
